"$schema" = "https://starship.rs/config-schema.json"

add_newline = true

continuation_prompt = "➜ "

format = """
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$fill\
$cmd_duration\
$character\
"""

[character]
error_symbol = "\n\\$"
success_symbol = "\n\\$"

[cmd_duration]
format = "[previous command took \\[$duration\\]]($style) "
min_time = 0
show_milliseconds = true
style = "black"

[directory]
format = "in [$path]($style) "
style = "yellow"
truncate_to_repo = false

[fill]
symbol = "  "

[git_branch]
format = "on [$branch]($style) "
style = "red"

[git_status]
format = "([\\[$staged$modified$untracked$up_to_date\\]]($style) )"
style = "blue"

[nodejs]
format = "with [$symbol($version )]($style)"
style = "green"
symbol = "\uE718 "

[username]
format = "[liam]($style) "
show_always = true
style_root = "green"
style_user = "green"
