#!/usr/bin/env node

// ----------------------------------------------
//   Author: Liam Howell
//   Description: Symlink Application icons
// ----------------------------------------------

const fs = require('fs');
const path = require('path');

const applications = [
  {
    application: 'Amazon Music',
    filename: 'amazon-music.icns',
    path: '/Applications/Amazon Music.app/Contents/Resources/morpho.icns'
  },
  {
    application: 'Notion',
    filename: 'notion.icns',
    path: '/Applications/Notion.app/Contents/Resources/electron.icns'
  },
  {
    application: 'Visual Studio Code',
    filename: 'vscode.icns',
    path: '/Applications/Visual Studio Code.app/Contents/Resources/Code.icns'
  }
];

const callback = function(application) {
  const resources = path.join(__dirname, '.resources');
  const resourceLocation = path.join(resources, application.filename);
  const directory = path.dirname(application.path);

  if (!fs.existsSync(directory)) {
    return;
  }

  const tmpFileName = `${Math.random().toString(36).substring(7)}.icns`;
  const tmpFileLocation = path.join(directory, tmpFileName);

  fs.copyFileSync(resourceLocation, tmpFileLocation);
  fs.renameSync(tmpFileLocation, path.join(directory, path.basename(application.path)));
  fs.utimesSync(path.join(directory, '../../'), new Date(), new Date());
};

applications.forEach((application) => callback(application));
