#!/bin/bash

# ----------------------------------------
#   Author: Liam Howell
#   Description: Configure some macOS default settings
#
#   1. GENERAL UI/UX
#   2. ACCESSORIES AND INPUT
#   3. ENERGY SAVING
#   4. SCREEN
#   5. FINDER
#   6. DOCK AND DASHBOARD
#   7. SAFARI AND WEBKIT
#   8. TIME MACHINE
#   9. ACTIVITY MONITOR
#   0. MAC APP STORE
#   1. CLEANUP
# ----------------------------------------

# ----------------------------------------
#   1. GENERAL UI/UX
# ----------------------------------------

## Set sidebar icon size to medium
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 2

## Always show scrollbars
defaults write NSGlobalDomain AppleShowScrollBars -string "WhenScrolling"

## Disable the over-the-top focus ring animation
defaults write NSGlobalDomain NSUseAnimatedFocusRing -bool false

## Adjust toolbar title rollover delay
defaults write NSGlobalDomain NSToolbarTitleViewRolloverDelay -float 0

## Increase window resize speed for Cocoa applications
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

## Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

## Expand print panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

## Save to disk (not to iCloud) by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

## Automatically quit printer app once the print jobs complete
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

## Disable the "Are you sure you want to open this application?" dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

## Disable Resume system-wide
defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false

## Disable automatic termination of inactive apps
defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true

## Disable automatic capitalization as it's annoying when typing code
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

## Disable smart dashes as they're annoying when typing code
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

## Disable automatic period substitution as it's annoying when typing code
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

## Disable smart quotes as they're annoying when typing code
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

## Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# ----------------------------------------
#   2. ACCESSORIES AND INPUT
# ----------------------------------------

## Trackpad: enable tap to click for this user and for the login screen
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

## Trackpad: map bottom right corner to right-click
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true

## Disable "natural" scrolling
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

## Increase sound quality for Bluetooth headphones/headsets
defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

# ----------------------------------------
#   3. ENERGY SAVING
# ----------------------------------------

## Enable lid wakeup
sudo pmset -a lidwake 1

## Restart automatically on power loss
sudo pmset -a autorestart 1

## Restart automatically if the computer freezes
sudo systemsetup -setrestartfreeze on

## Sleep the display after 10 minutes
sudo pmset -a displaysleep 10

## Set machine sleep to 5 minutes on battery
sudo pmset -b sleep 5

## Remove the sleep image file to save disk space
## Create a zero-byte file instead and make sure it can't be rewritten
sudo rm /private/var/vm/sleepimage
sudo touch /private/var/vm/sleepimage
sudo chflags uchg /private/var/vm/sleepimage

# ----------------------------------------
#   4. SCREEN
# ----------------------------------------

## Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

## Save screenshots to the desktop
defaults write com.apple.screencapture location -string "${HOME}/Desktop"

## Save screenshots in PNG format
defaults write com.apple.screencapture type -string "png"

## Enable subpixel font rendering on non-Apple LCDs
defaults write NSGlobalDomain AppleFontSmoothing -int 1

## Enable HiDPI display modes
sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true

# ----------------------------------------
#   5. FINDER
# ----------------------------------------

## Disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true

## Set Home as the default location for new Finder windows
defaults write com.apple.finder NewWindowTarget -string "PfLo"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"

## Hide icons for hard drives, servers, and removable media on the desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowMountedServersOnDesktop -bool false
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool false

## Show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

## Hide status bar
defaults write com.apple.finder ShowStatusBar -bool false

## Hide path bar
defaults write com.apple.finder ShowPathbar -bool false

## Keep folders on top when sorting by name
defaults write com.apple.finder _FXSortFoldersFirst -bool true

## When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

## Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

## Enable spring loading for directories
defaults write NSGlobalDomain com.apple.springing.enabled -bool true

## Remove the spring loading delay for directories
defaults write NSGlobalDomain com.apple.springing.delay -float 0

## Avoid creating .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

## Disable disk image verification
defaults write com.apple.frameworks.diskimages skip-verify -bool true
defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

## Use list view in all Finder windows by default
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

## Disable the warning before emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false

# ----------------------------------------
#   6. DOCK AND DASHBOARD
# ----------------------------------------

## Set the icon size of Dock items to 36 pixels
defaults write com.apple.dock tilesize -int 36

## Change minimize/maximize window effect
defaults write com.apple.dock mineffect -string "genie"

## Disable minimizing windows into their application icon
defaults write com.apple.dock minimize-to-application -bool false

## Enable spring loading for all Dock items
defaults write com.apple.dock enable-spring-load-actions-on-all-items -bool true

## Show indicator lights for open applications in the Dock
defaults write com.apple.dock show-process-indicators -bool true

## Speed up Mission Control animations
defaults write com.apple.dock expose-animation-duration -float 0.1

## Don't group windows by application in Mission Control
defaults write com.apple.dock expose-group-by-app -bool false

## Disable Dashboard
defaults write com.apple.dashboard mcx-disabled -bool true

## Don't show Dashboard as a Space
defaults write com.apple.dock dashboard-in-overlay -bool true

## Don't automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

## Remove the auto-hiding Dock delay
defaults write com.apple.dock autohide-delay -float 0

## Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

## Don't show recent applications in Dock
defaults write com.apple.dock show-recents -bool false

## Disable the Launchpad gesture (pinch with thumb and three fingers)
defaults write com.apple.dock showLaunchpadGestureEnabled -int 0

## Put the Dock on the bottom of the screen
defaults write com.apple.dock "orientation" -string "bottom"

# ----------------------------------------
#   7. SAFARI AND WEBKIT
# ----------------------------------------

## Don't send search queries to Apple
defaults write com.apple.Safari UniversalSearchEnabled -bool false
defaults write com.apple.Safari SuppressSearchSuggestions -bool true

## Show the full URL in the address bar
defaults write com.apple.Safari ShowFullURLInSmartSearchField -bool true

## Set Safari's home page to `about:blank` for faster loading
defaults write com.apple.Safari HomePage -string "about:blank"

## Prevent Safari from opening 'safe' files automatically after downloading
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

## Hide Safari's bookmarks bar by default
defaults write com.apple.Safari ShowFavoritesBar -bool false

## Hide Safari's sidebar in Top Sites
defaults write com.apple.Safari ShowSidebarInTopSites -bool false

## Disable Safari's thumbnail cache for History and Top Sites
defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2

## Enable Safari's debug menu
defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

## Make Safari's search banners default to Contains instead of Starts With
defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

## Remove useless icons from Safari's bookmarks bar
defaults write com.apple.Safari ProxiesInBookmarksBar "()"

## Enable the Develop menu and the Web Inspector in Safari
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true

## Add a context menu item for showing the Web Inspector in web views
defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

## Enable continuous spellchecking
defaults write com.apple.Safari WebContinuousSpellCheckingEnabled -bool true

## Disable auto-correct
defaults write com.apple.Safari WebAutomaticSpellingCorrectionEnabled -bool false

## Disable AutoFill
defaults write com.apple.Safari AutoFillFromAddressBook -bool false
defaults write com.apple.Safari AutoFillPasswords -bool false
defaults write com.apple.Safari AutoFillCreditCardData -bool false
defaults write com.apple.Safari AutoFillMiscellaneousForms -bool false

## Warn about fraudulent websites
defaults write com.apple.Safari WarnAboutFraudulentWebsites -bool true

## Disable plug-ins
defaults write com.apple.Safari WebKitPluginsEnabled -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2PluginsEnabled -bool false

## Disable Java
defaults write com.apple.Safari WebKitJavaEnabled -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabled -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabledForLocalFiles -bool false

## Block pop-up windows
defaults write com.apple.Safari WebKitJavaScriptCanOpenWindowsAutomatically -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaScriptCanOpenWindowsAutomatically -bool false

## Disable auto-playing video
defaults write com.apple.Safari WebKitMediaPlaybackAllowsInline -bool false
defaults write com.apple.SafariTechnologyPreview WebKitMediaPlaybackAllowsInline -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2AllowsInlineMediaPlayback -bool false
defaults write com.apple.SafariTechnologyPreview com.apple.Safari.ContentPageGroupIdentifier.WebKit2AllowsInlineMediaPlayback -bool false

## Enable "Do Not Track"
defaults write com.apple.Safari SendDoNotTrackHTTPHeader -bool true

## Update extensions automatically
defaults write com.apple.Safari InstallExtensionUpdatesAutomatically -bool true

# ----------------------------------------
#   8. TIME MACHINE
# ----------------------------------------

## Prevent Time Machine from prompting to use new hard drives as backup volume
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

## Disable local Time Machine backups
hash tmutil &> /dev/null && sudo tmutil disablelocal

# ----------------------------------------
#   9. ACTIVITY MONITOR
# ----------------------------------------

## Show the main window when launching Activity Monitor
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

## Visualize CPU usage in the Activity Monitor Dock icon
defaults write com.apple.ActivityMonitor IconType -int 5

## Show all processes in Activity Monitor
defaults write com.apple.ActivityMonitor ShowCategory -int 0

## Sort Activity Monitor results by CPU usage
defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
defaults write com.apple.ActivityMonitor SortDirection -int 0

# ----------------------------------------
#   0. MAC APP STORE
# ----------------------------------------

## Enable the WebKit Developer Tools in the Mac App Store
defaults write com.apple.appstore WebKitDeveloperExtras -bool true

## Enable Debug Menu in the Mac App Store
defaults write com.apple.appstore ShowDebugMenu -bool true

## Enable the automatic update check
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

## Check for software updates daily, not just once per week
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

## Download newly available updates in background
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

## Install System data files & security updates
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1

## Turn on app auto-update
defaults write com.apple.commerce AutoUpdate -bool true

## Allow the App Store to reboot machine on macOS updates
defaults write com.apple.commerce AutoUpdateRestartRequired -bool true

# ----------------------------------------
#   1. CLEANUP
# ----------------------------------------

killall ActivityMonitor &> /dev/null
killall cfprefsd &> /dev/null
killall Dock &> /dev/null
killall Finder &> /dev/null
killall Safari &> /dev/null
killall SoftwareUpdate &> /dev/null
killall SystemUIServer &> /dev/null
